version: "3.9"

services:
  django:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/cryptocurrency_price_tracker
    ports:
      - "8000:8000"